apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: course-workload-estimator-

namespace: course-workload-estimator

# Generate an app-name to inject into the OCIRepository url. This is not added to the cluster.
configMapGenerator:
  - name: app-name
    literals:
      - app-name=course-workload-estimator
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

components:
  - ../../components/replacements/app-url
