---
apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app1
  namespace: app1
spec:
  interval: 5m
  releaseName: app1
  chart:
    spec:
      chart: app1
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: helm-charts
        namespace: flux-system
    valuesFrom:
      - kind: ConfigMap
        name: values-latest
        valuesKey: values.yaml
  dependsOn: []
