apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# Prefix all resources with this name.
namePrefix: app1-

# Add all resources to this namespace.
namespace: app1

# Generate an app-name config for re-use. Resource is not added to the cluster.
configMapGenerator:
  - name: app-name
    literals:
      - appName="app1"
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

components:
  # - ../../components/generators/ssl-certificates

  # Update the OCIRepository URL based on the app-name stored in the ConfigMap.
  - ../../components/transformers/oci-url

  # Required for VaultAuth role and serviceaccounts
  # - ../../components/generators/vault-auth
