# Update the OCIRepository URL based on the app name stored in a ConfigMap.
---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: ConfigMap
      name: app-name
      fieldPath: data.app-name
    targets:
      - select:
          kind: OCIRepository
        fieldPaths:
          - spec.url
        options:
          delimiter: "/"
          index: 5
