apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - namespace.yaml - namespace created by flux bootstrap
  - helmrepository.yaml
  - helmrelease.yaml
  - vault-connection.yaml

namePrefix: vault-secrets-operator-

namespace: vault-secrets-operator-system

# update generated vault-connection name
configurations:
  - kustomizeconfig.yaml

components:
  # Required for VaultAuth role and serviceaccounts
  - ../../components/generators/vault-auth
