# This file is for teaching kustomize how to substitute names in the HelmRelease CRD
#
nameReference:

- kind: ServiceAccount
  fieldSpecs:
    - path: spec/kubernetes/serviceAccount
      kind: VaultAuthGlobal

- kind: HelmRepository
  fieldSpecs:
  - path: spec/chart/spec/sourceRef/name
    kind: HelmRelease

- kind: VaultConnection
  fieldSpecs:
    - path: spec/vaultConnectionRef
      kind: VaultAuthGlobal
