apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - namespace.yaml - namespace created by flux bootstrap
  - ./service


# Locate all resources in a namespace (to ensure secrets are located correctly)
#
namespace: vault-secrets-operator-system

patches:
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
    patch: |-
      - op: add
        path: /spec/targetNamespace
        value: vault-secrets-operator-system

