# For secrets in the vault secrets operator namespace only
#
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vaultconnection
spec:
  address: https://vault.ltc.bcit.ca:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuthGlobal
metadata:
  name: vaultauthglobal
spec:
  allowedNamespaces:
    - "*"
  defaultAuthMethod: kubernetes
  kubernetes:
    mount: kubernetes
    audiences:
    - vault
    role: vaultauth
    serviceAccount: serviceaccount
    tokenExpirationSeconds: 600
  vaultConnectionRef:
    name: vaultconnection
