# Vault secrets operator VaultAuth configuration
#   - Requires `vault-config` kubernetes auths to match
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vaultauth
spec:
  kubernetes:
    serviceAccount: serviceaccount
    role: vaultauth
  vaultAuthGlobalRef:
    name: vaultauthglobal
    allowDefault: true
    namespace: vault-secrets-operator-system
