---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  # - ./service

namePrefix: rancher-

# Locate all resources in a namespace (to ensure secrets are located correctly)
#
namespace: cattle-system

# components:

  # TLS required for Rancher
  # - ../../../components/tls

  # Vault token to decrypt secrets
  # - ../../../components/sops-vault-token

  # Required for VaultAuth role and serviceaccounts
  # - ../../../components/vault-auth
