apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-tokenauth
  namespace: vault-secrets-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-tokenauth
  namespace: vault-secrets-operator-system
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-tokenauth
  namespace: vault-secrets-operator-system
  annotations:
    kubernetes.io/service-account.name: vault-tokenauth
type: kubernetes.io/service-account-token
