---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - crb-sa-vault-tokenauth.yaml

  # Deploy crd's required for flux-based installation
  - https://github.com/hashicorp/vault-secrets-operator//config/crd/?timeout=120

# Locate all resources in a namespace (to ensure secrets are located correctly)
#
namespace: vault-secrets-operator-system
