apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  config.fluxcd.io/workload-type: infrastructure

resources:
  - flux
  # - ./longhorn

  # longhorn uninstall requires a patch:
  #   `kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag`
  # CRD's must also be deleted manually right after removing longhorn
  #   `./longhorn/uninstall-crds.sh`

  - ./vault-secrets-operator