# Create a secret for the sops decryption key
#
---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - token.yaml


# Teach kustomize how to update generated names
#
configurations:
  - kustomizeconfig.yaml
