---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sops-vault-token
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  refreshAfter: 6h
  mount: ltc-infrastructure
  path: flux-config/sops-vault-token
  destination:
    name: sops-vault-token
    create: true
