# This file is for teaching kustomize how to substitute names
nameReference:

# Add the name of the OCIRepository to the HelmRelease chartRef
- kind: OCIRepository
  fieldSpecs:
    - kind: HelmRelease
      path: spec/chartRef/name

# Add the namespace to the HelmRelease chartRef
namespace:
- kind: HelmRelease
  path: spec/chartRef/namespace
  create: true
