apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./namespace.yaml
  # - ./ocirepository.yaml

# Teach kustomize how to update generated names
configurations:
  - kustomizeconfig.yaml
