# Create a tls secret for the star.ltc.bcit.ca certificate
#
---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - star-ltc-bcit-ca.yaml

# Teach kustomize how to update generated names
#
configurations:
  - kustomizeconfig.yaml
  