---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: longhorn-


# Provide service-specific parameters
#
patches:
  - target:
      kind: GitRepository
    patch: |-
      - op: replace
        path: /spec/url
        value: https://issues.ltc.bcit.ca/ltc-infrastructure/longhorn


# Incorporate re-usable components
#
components:

  # Configure Mattermost notifications and GitLab webhook
  - ../../../components/notifications

  # Vault token to decrypt secrets
  - ../../../components/sops-vault-token

  # Generate the GitLab project access token `dependabot` secret 
  - ../../../components/tokens

  # Required for VaultAuth role and serviceaccounts
  - ../../../components/vault-auth


# Config map used to patch resources
#
# `gitlabProjectAccessToken` is used to patch "dependabot" secrets:
#   - GitRepository `spec.secretRef.name` 
#   - VaultStaticSecret `spec.path`
#   - VaultStaticSecret `spec.destination.name`
#
configMapGenerator:
  - name: gitlab-dependabot
    literals:
      - gitlabProjectAccessToken=longhorn-dependabot

# Replace fields in other resources.
replacements:
  - source:
      kind: ConfigMap
      name: gitlab-dependabot
      fieldPath: data.gitlabProjectAccessToken
    targets:
      - select:
          kind: VaultStaticSecret
          name: dependabot
        fieldPaths:
          - spec.path
          - spec.destination.name
      - select:
          kind: GitRepository
          name: git-repository
        fieldPaths:
          - spec.secretRef.name
